### PR TITLE
feat: Create an Angular version of the React library

### PR DESCRIPTION
**Pull request by danmt**

### CODE REVIEW

**Comment by danmt** [comment]
Hey @jordansexton I got an initial working version. 

It isn't ready for review yet because I'm not really sure how to test this. I wrote it using Nx workspace (the tool I'm familiar with for monorepos) and it works there, I'm trying to move it to the @solana/wallet-adapter workspace.

I haven't used Lerna before but here's what I did:

- Copy/paste the base structure of `packages/react`
- Replace React deps for Angular specific deps
- Run `yarn install --frozen-lockfile` in the root path
- Run `yarn build`

It looks like it went alright, how do you suggest for me to test this before raising the actual PR? I was thinking on creating my own npm package, publish it and test back in my "example app". Seems a bit overkill so I figured you may have a better alternative.

**Comment by jordaaash** [comment]
This PR has been opened against the master branch of your fork rather than the source. The steps you outlined sound good though. I don't think you have to use `--frozen-lockfile` though since you are adding your deps?

A straightforward way to test it might be to create an `angular-starter` package as well, and then you can make sure everything works while also planning out the UI.

**Comment by danmt** [comment]
Right on, thanks for the ack bro.

Ohh yeah, created this PR just as a mean of communication. I'll change the target as soon as I get this to work in the lerna workspace. So far, not so much luck, decided to read a bit about lerna before diving more.

**Comment by jordaaash** [comment]
Ah, okay. To be honest, I know very little about lerna and the library doesn't do much with it except build. I just saw it worked with yarn workspaces out of the box and figured I'd give it a shot 😅 

What's the typical way to create a quick app in Angular land? I imagine there's something like CRA

**Comment by danmt** [comment]
I won't lie, I'm taking this as a chance to learn a new thing, so I'm actually kinda excited about it. 

Angular has a CLI that makes it easy as long as you're not exploring outside of Angular's "perfect world". That doesn't stick so much in this case lol. When you're doing something like this, the recommendation is to go with [Nx workspaces](https://github.com/nrwl/nx) which I used to bootstrap the code that's working. Now I'm just trying to fill the gaps so it works with Lerna.

BTW - Nx is quite a tool, might be worth taking a look at it.

**Pull request merged**
